[client]
showErrorDetails = false

[global]
showWarningOnDirectExecution = false

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[server]
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "none"
enableStaticServing = true

[theme]
primaryColor="#FF4B4B"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#31333F"
font="sans serif"
